---
deployment:
  tasks:
    - export DEPLOYPATH=/home/flae9220/public_html
    - bin/cp/ -R app $DEPLOYPATH
    - bin/cp/ -R public $DEPLOYPATH
    - /bin/cp -R .vscode $DEPLOYPATH
    /bin/cp spark $DEPLOYPATH