---
deployment:
  task:
    - export DEPLOYPATH=/home/flae9220/public_html
    - bin/cp/ -R app $DEPLOYPATH
    - bin/cp/ -R public $DEPLOYPATH
    - bin/cp/ -R system $DEPLOYPATH
    - bin/cp/ -R writable $DEPLOYPATH
